import React, {useEffect, useMemo, useState} from 'react'
import {createRoot} from 'react-dom/client'
import {BrowserRouter, Routes, Route, NavLink, useLocation, useNavigate} from 'react-router-dom'
import {LayoutDashboard, BookOpenCheck, ClipboardCheck, ShieldCheck, UserRound, Lightbulb, MessageSquareText, Users, BookOpen, BarChart3, Map, ServerCog, Menu, Search, Bell, LogOut, CloudSun, ArrowRight, CheckCircle2, LockKeyhole, Activity, BrainCircuit, TrendingUp, DatabaseZap, RefreshCw, Upload, Filter, Award, GraduationCap, UserCog, ChevronRight} from 'lucide-react'
import {ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip, BarChart, Bar, PieChart, Pie, Cell} from 'recharts'
import './index.css'

const blue='#0868df'
const profiles={
 trainee:{name:'Rahul Sharma', initials:'RS', label:'Trainee', department:'Forecasting', id:'IMD-TR-10482'},
 trainer:{name:'Dr. Meera Iyer', initials:'MI', label:'Trainer', department:'Training & Capacity Building', id:'IMD-TN-00211'},
 admin:{name:'Amit Verma', initials:'AV', label:'Admin', department:'Administration', id:'IMD-AD-00034'}
}
const courses=[
 {id:1,title:'Radar Fundamentals',level:'Beginner',category:'Radar',desc:'Understand radar systems, reflectivity, Doppler principles and operational interpretation.',modules:6,hours:12,progress:72,recommended:true},
 {id:2,title:'Doppler Radar Interpretation',level:'Intermediate',category:'Radar',desc:'Interpret Doppler velocity and severe-weather signatures for operational forecasting.',modules:8,hours:16,progress:36,recommended:true},
 {id:3,title:'Satellite Meteorology',level:'Intermediate',category:'Satellite',desc:'Analyze satellite imagery, cloud patterns and products used in weather forecasting.',modules:7,hours:14,progress:58,recommended:true},
 {id:4,title:'Numerical Weather Prediction',level:'Advanced',category:'NWP',desc:'Explore model outputs, ensemble forecasts and operational NWP workflows.',modules:10,hours:22,progress:18},
 {id:5,title:'Climate Data & Extremes',level:'Intermediate',category:'Climate',desc:'Work with climate datasets and identify extreme-weather indicators.',modules:7,hours:15,progress:0},
 {id:6,title:'Forecast Communication & Warnings',level:'Beginner',category:'Forecasting',desc:'Build clear, timely and audience-aware weather warnings and advisories.',modules:5,hours:9,progress:84,recommended:true},
]
const participation=[{m:'Jan',v:180},{m:'Feb',v:220},{m:'Mar',v:265},{m:'Apr',v:310},{m:'May',v:355},{m:'Jun',v:402},{m:'Jul',v:438},{m:'Aug',v:465}]
const completion=[{name:'Completed',value:72},{name:'In Progress',value:18},{name:'Not Started',value:10}]
const heatRows=[['Delhi',[3,2,3,1,3,2]],['Mumbai',[2,3,3,2,3,1]],['Chennai',[3,1,3,3,2,3]],['Kolkata',[3,2,3,1,1,3]],['Nagpur',[2,3,3,1,2,2]],['Guwahati',[3,2,3,2,3,2]]]

function App(){return <Routes><Route path="*" element={<RouterView/>}/></Routes>}
function RouterView(){const loc=useLocation(); return loc.pathname==='/'||loc.pathname==='/login'?<Public/>:<Portal/>}
function Brand({compact=false}){const nav=useNavigate();return <button onClick={()=>nav('/')} className="group flex items-center gap-3 text-left outline-none" title="Go to Capacity Connect home"><div className="w-10 h-10 rounded-xl bg-gradient-to-br from-amber-300 to-blue-700 grid place-items-center text-white shadow transition-all duration-200 group-hover:scale-105 group-hover:shadow-[0_0_20px_rgba(8,104,223,.35)]"><CloudSun size={21}/></div><div><div className="font-extrabold tracking-tight text-[#163b69]">CAPACITY <span className="text-[#0868df]">CONNECT</span></div>{!compact&&<div className="text-[10px] text-slate-500">Digital Learning & Competency Portal</div>}</div></button>}
function Public(){const nav=useNavigate(); const login=location.pathname==='/login';return <div className="min-h-screen bg-white"><div className="bg-[#0c315f] text-white px-6 py-2 text-xs font-bold tracking-wide">INDIA METEOROLOGICAL DEPARTMENT · MINISTRY OF EARTH SCIENCES</div><header className="h-20 border-b border-slate-200 flex items-center justify-between px-5 lg:px-12 bg-white"><Brand/><nav className="hidden md:flex items-center gap-7 text-sm text-slate-600"><button onClick={()=>nav('/')} className="nav-hover">Home</button><button className="nav-hover">About</button><button className="nav-hover">Learning</button><button className="nav-hover">Contact</button><button onClick={()=>nav('/login')} className="interactive bg-[#0868df] text-white rounded-md px-5 py-2.5 font-semibold">Login</button></nav></header>{login?<Login/>:<Landing/>}</div>}
function Landing(){const nav=useNavigate();return <main><section className="grid lg:grid-cols-2 min-h-[calc(100vh-100px)] bg-white"><div className="px-8 sm:px-14 lg:px-20 py-16 flex flex-col justify-center"><div className="inline-flex items-center gap-2 w-fit bg-blue-50 text-blue-700 px-3 py-1.5 rounded-full text-xs font-bold mb-6"><ShieldCheck size={14}/> Secure · Optimized · IMD Specialized</div><h1 className="text-5xl sm:text-6xl font-black leading-[.95] text-[#163b69]">Digital Capacity<br/><span className="text-[#0868df]">Building</span> for IMD</h1><p className="text-xl font-semibold text-slate-700 mt-5 max-w-xl">Empowering meteorological personnel with skills, knowledge and competencies for a safer, more resilient India.</p><p className="text-sm leading-7 text-slate-500 mt-4 max-w-xl">A specialized learning management and competency intelligence portal with personalized recommendations, department analytics and performance-aware platform optimization.</p><div className="flex flex-wrap gap-3 mt-8"><button onClick={()=>nav('/login')} className="interactive bg-[#0868df] text-white px-6 py-3 rounded-md font-bold shadow-lg shadow-blue-200">Get Started <ArrowRight className="inline ml-2" size={16}/></button><button onClick={()=>nav('/dashboard')} className="interactive border border-slate-300 px-6 py-3 rounded-md font-bold text-slate-700">View Trainee Demo</button></div><div className="grid grid-cols-4 gap-4 mt-10 max-w-xl">{[[BookOpen,'Learn'],[ClipboardCheck,'Assess'],[Lightbulb,'Recommend'],[CheckCircle2,'Certify']].map(([I,t])=><button key={t} onClick={()=>nav('/login')} className="interactive text-center text-xs font-bold text-slate-600 rounded-xl p-2"><I className="mx-auto mb-2 text-[#0868df]" size={23}/>{t}</button>)}</div></div><div className="relative min-h-[520px] bg-cover bg-center" style={{backgroundImage:"linear-gradient(90deg,rgba(255,255,255,.92),rgba(255,255,255,0) 40%),url('/assets/storm-reference.jpg')"}}><div className="absolute right-10 bottom-12 text-white font-black text-2xl leading-tight drop-shadow-lg">Better People<br/>Better Forecasts<br/>A Safer Tomorrow</div><div className="absolute left-8 top-8 grid grid-cols-2 gap-3"><MiniStat icon={<BrainCircuit/>} label="Smart Recommendations"/><MiniStat icon={<Activity/>} label="Load-Aware Platform"/></div></div></section></main>}
function MiniStat({icon,label}){return <div className="bg-white/90 backdrop-blur border border-white rounded-xl p-3 shadow-xl w-44 hover:-translate-y-1 transition-transform"><div className="text-[#0868df] mb-2">{React.cloneElement(icon,{size:18})}</div><div className="text-xs font-bold text-slate-700">{label}</div></div>}
function Login(){const nav=useNavigate(); const [role,setRole]=useState('trainee'); const p=profiles[role]; const submit=()=>{localStorage.setItem('ccRole',role);nav('/dashboard')};return <div className="min-h-[calc(100vh-100px)] grid place-items-center bg-gradient-to-br from-blue-50 to-slate-50 px-4 py-10"><div className="w-full max-w-md bg-white border border-slate-200 rounded-2xl shadow-xl p-8"><div className="text-center mb-6"><div className="mx-auto w-12 h-12 rounded-xl bg-blue-50 grid place-items-center text-blue-700"><LockKeyhole/></div><h2 className="text-2xl font-extrabold mt-3">Welcome Back</h2><p className="text-sm text-slate-500">Select your role to preview the corresponding portal</p></div><div className="grid grid-cols-3 gap-2 mb-6">{[['trainee',GraduationCap,'Trainee'],['trainer',UserCog,'Trainer'],['admin',ShieldCheck,'Admin']].map(([r,I,label])=><button key={r} onClick={()=>setRole(r)} className={`role-tab ${role===r?'role-active':''}`}><I size={18}/><span>{label}</span></button>)}</div><div className="rounded-xl bg-slate-50 border border-slate-200 p-3 mb-5 flex items-center gap-3"><div className="w-10 h-10 rounded-full bg-slate-300 text-white grid place-items-center text-xs font-bold">{p.initials}</div><div><div className="font-bold text-sm">{p.name}</div><div className="text-[11px] text-slate-500">{p.label} · IMD</div></div></div><label className="text-xs font-bold text-slate-600">Email or Employee ID</label><input className="w-full h-11 mt-2 mb-4 border rounded-lg px-3 outline-blue-500" defaultValue={p.id}/><label className="text-xs font-bold text-slate-600">Password</label><input type="password" className="w-full h-11 mt-2 border rounded-lg px-3 outline-blue-500" defaultValue="password"/><button onClick={submit} className="interactive w-full mt-5 bg-[#0868df] text-white h-11 rounded-lg font-bold">Login as {p.label}</button><button onClick={submit} className="interactive w-full mt-3 h-11 rounded-lg border border-slate-300 font-bold text-slate-700">Login with Government SSO</button><div className="text-center text-xs text-blue-600 mt-4">Forgot Password?</div><div className="text-center text-[10px] text-slate-400 mt-8">Demo role switcher · JWT / RBAC-ready architecture</div></div></div>}

function Portal(){const [mobile,setMobile]=useState(false);const role=localStorage.getItem('ccRole')||'trainee';const p=profiles[role];const nav=useNavigate();const logout=()=>{localStorage.removeItem('ccRole');nav('/login')};return <div className="min-h-screen bg-[#f5f8fc]"><header className="h-16 bg-white border-b border-slate-200 flex items-center justify-between px-4 lg:px-6 sticky top-0 z-30"><div className="flex items-center gap-3"><button className="lg:hidden interactive p-2" onClick={()=>setMobile(!mobile)}><Menu/></button><Brand compact/></div><div className="flex items-center gap-3"><label className="hidden md:flex items-center gap-2 border border-slate-200 rounded-lg px-3 h-9 w-60 text-slate-400 focus-within:border-blue-400 focus-within:ring-2 focus-within:ring-blue-100 transition-all"><Search size={15}/><input aria-label="Search courses and skills" className="w-full bg-transparent outline-none text-xs text-slate-700 placeholder:text-slate-400" placeholder="Search courses, skills..." /></label><button className="interactive p-2 rounded-lg" title="Notifications"><Bell size={18}/></button><button onClick={()=>nav('/profile')} className="interactive flex items-center gap-2 text-left rounded-lg p-1.5"><div className="w-9 h-9 rounded-full bg-gradient-to-br from-slate-500 to-slate-300 text-white grid place-items-center text-xs font-bold">{p.initials}</div><div className="hidden sm:block"><div className="text-xs font-bold">{p.name}</div><div className="text-[10px] text-slate-500">{p.label} · IMD</div></div></button><button onClick={logout} className="interactive hidden sm:block p-2 rounded-lg text-slate-500" title="Logout"><LogOut size={17}/></button></div></header><div className="flex"><Sidebar mobile={mobile} close={()=>setMobile(false)} role={role}/><main className="flex-1 min-w-0 p-4 lg:p-7"><Routes><Route path="/dashboard" element={<RoleDashboard role={role}/>}/><Route path="/learning" element={<Learning/>}/><Route path="/course/:id" element={<ManageCourse/>}/><Route path="/recommended" element={<Recommended/>}/><Route path="/assessment" element={<Assessment/>}/><Route path="/manage-assessments" element={<TrainerAssessments/>}/><Route path="/certificate" element={<Certificate/>}/><Route path="/profile" element={<Profile role={role}/>}/><Route path="/feedback" element={<Feedback/>}/><Route path="/trainer" element={<Trainer/>}/><Route path="/admin" element={<Admin/>}/><Route path="/heatmap" element={<Heatmap/>}/><Route path="/optimization" element={<Optimization/>}/><Route path="/users" element={<UserManagement/>}/></Routes></main></div></div>}
const traineeNav=[['/dashboard',LayoutDashboard,'Dashboard'],['/learning',BookOpenCheck,'My Learning'],['/assessment',ClipboardCheck,'Assessments'],['/recommended',Lightbulb,'Recommended'],['/certificate',CheckCircle2,'Certificates'],['/profile',UserRound,'My Profile'],['/feedback',MessageSquareText,'Feedback']]
const trainerNav=[['/dashboard',LayoutDashboard,'Trainer Dashboard'],['/trainer',BrainCircuit,'Trainer Studio'],['/learning',BookOpen,'Learning Content'],['/manage-assessments',ClipboardCheck,'Manage Assessments'],['/profile',UserRound,'My Profile']]
const adminNav=[['/dashboard',LayoutDashboard,'Admin Dashboard'],['/admin',BarChart3,'Analytics'],['/heatmap',Map,'Competency Heatmap'],['/optimization',ServerCog,'Load Optimization'],['/users',Users,'User Management'],['/profile',UserRound,'My Profile']]
function Sidebar({mobile,close,role}){const items=role==='admin'?adminNav:role==='trainer'?trainerNav:traineeNav;return <aside className={`${mobile?'fixed inset-y-16 left-0 z-20 shadow-xl':'hidden'} lg:block w-64 bg-white border-r border-slate-200 min-h-[calc(100vh-64px)] p-4`}>{<div className="mb-5 px-2"><div className="text-[10px] uppercase tracking-widest text-slate-400 font-bold">{profiles[role].label} Workspace</div><div className="text-sm font-extrabold text-[#163b69] mt-1">Capacity Connect</div></div>}{items.map(([to,I,label])=><NavLink onClick={close} key={to} to={to} className={({isActive})=>`side-link ${isActive?'side-active':''}`}><I size={17}/><span>{label}</span><ChevronRight className="ml-auto opacity-0 group-hover:opacity-50" size={14}/></NavLink>)}{role==='trainee'&&<div className="mt-6 p-3 rounded-xl bg-blue-50 border border-blue-100"><div className="text-xs font-bold text-blue-800">Your competency score</div><div className="text-2xl font-black text-blue-700 mt-1">76%</div><div className="text-[10px] text-blue-600 mt-1">12% improvement this quarter</div></div>}{role==='trainer'&&<div className="mt-6 p-3 rounded-xl bg-emerald-50 border border-emerald-100"><div className="text-xs font-bold text-emerald-800">Active learners</div><div className="text-2xl font-black text-emerald-700 mt-1">184</div></div>}{role==='admin'&&<div className="mt-6 p-3 rounded-xl bg-slate-50 border"><div className="text-xs font-bold">Platform health</div><div className="text-2xl font-black mt-1">99.96%</div><div className="text-[10px] text-emerald-600 mt-1">All systems operational</div></div>}</aside>}
function PageHead({title,sub,children}){return <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4 mb-6"><div><h1 className="text-2xl font-black text-[#163b69]">{title}</h1><p className="text-sm text-slate-500 mt-1">{sub}</p></div>{children}</div>}
function Card({children,className=''}){return <div className={`bg-white border border-slate-200 rounded-xl shadow-sm ${className}`}>{children}</div>}
function Kpi({icon:I,num,label,trend}){return <Card className="p-4 interactive"><div className="flex items-center justify-between"><div className="w-9 h-9 rounded-lg bg-blue-50 text-blue-700 grid place-items-center"><I size={18}/></div>{trend&&<span className="text-[10px] font-bold text-emerald-600">{trend}</span>}</div><div className="text-2xl font-black mt-3">{num}</div><div className="text-xs text-slate-500 mt-1">{label}</div></Card>}
function RoleDashboard({role}){if(role==='admin')return <Admin/>;if(role==='trainer')return <TrainerDashboard/>;return <TraineeDashboard/>}
function TraineeDashboard(){const nav=useNavigate();return <><PageHead title="Good morning, Rahul 👋" sub="Your personalized learning and competency overview."/><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4"><Kpi icon={BookOpen} num="6" label="Courses Enrolled"/><Kpi icon={Activity} num="48%" label="Overall Progress" trend="+8% this month"/><Kpi icon={Award} num="3" label="Certificates"/><Kpi icon={Lightbulb} num="4" label="Recommended"/></div><div className="grid xl:grid-cols-[1.35fr_.65fr] gap-5 mt-5"><Card className="p-5"><div className="flex items-center justify-between"><div><h3 className="font-extrabold">Continue Learning</h3><p className="text-xs text-slate-500 mt-1">Doppler Radar Interpretation · 36% complete</p></div><button onClick={()=>nav('/learning')} className="interactive text-xs font-bold text-blue-700">View all</button></div><div className="mt-5"><div className="flex justify-between text-xs font-bold"><span>Doppler Radar Interpretation</span><span>36%</span></div><div className="h-2 bg-slate-100 rounded-full mt-2"><div className="h-2 bg-blue-600 rounded-full" style={{width:'36%'}}/></div></div><button onClick={()=>nav('/learning')} className="interactive mt-5 bg-blue-600 text-white px-4 py-2.5 rounded-lg text-xs font-bold">Resume Course <ArrowRight className="inline ml-1" size={14}/></button></Card><Card className="p-5"><h3 className="font-extrabold">Competency Snapshot</h3><div className="space-y-4 mt-5">{[['Forecasting',80],['Satellite',60],['Radar',72],['NWP',42]].map(([x,v])=><div key={x}><div className="flex justify-between text-xs"><span>{x}</span><b>{v}%</b></div><div className="h-2 bg-slate-100 rounded-full mt-1"><div className="h-2 bg-blue-500 rounded-full" style={{width:v+'%'}}/></div></div>)}</div><button onClick={()=>nav('/recommended')} className="interactive w-full mt-5 border border-blue-200 text-blue-700 py-2 rounded-lg text-xs font-bold">Improve your skill gaps</button></Card></div><div className="grid xl:grid-cols-3 gap-5 mt-5">{courses.filter(c=>c.recommended).slice(0,3).map(c=><CourseCard key={c.id} c={c}/>)}</div></>}
function TrainerDashboard(){const nav=useNavigate();return <><PageHead title="Trainer Dashboard" sub="Manage learning content, assessments and trainee progress."/><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4"><Kpi icon={Users} num="184" label="Active Learners" trend="+12 this week"/><Kpi icon={BookOpen} num="18" label="Published Courses"/><Kpi icon={ClipboardCheck} num="9" label="Assessments"/><Kpi icon={BrainCircuit} num="27" label="AI Draft Questions"/></div><div className="grid xl:grid-cols-2 gap-5 mt-5"><Card className="p-5"><h3 className="font-extrabold">Trainer Actions</h3><div className="grid sm:grid-cols-2 gap-3 mt-4"><button onClick={()=>nav('/trainer')} className="interactive dashboard-action"><BrainCircuit/><span>Generate MCQs</span></button><button onClick={()=>nav('/learning')} className="interactive dashboard-action"><BookOpen/><span>Manage Content</span></button><button onClick={()=>nav('/manage-assessments')} className="interactive dashboard-action"><ClipboardCheck/><span>Manage Assessments</span></button><button onClick={()=>nav('/profile')} className="interactive dashboard-action"><UserRound/><span>Trainer Profile</span></button></div></Card><Card className="p-5"><h3 className="font-extrabold">Learner Progress</h3><div className="h-56 mt-3"><ResponsiveContainer width="100%" height="100%"><BarChart data={[{x:'Radar',v:76},{x:'Satellite',v:68},{x:'NWP',v:51},{x:'Climate',v:62}]}><XAxis dataKey="x" fontSize={11}/><YAxis fontSize={11}/><Tooltip/><Bar dataKey="v" fill={blue} radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></Card></div></>}
function CourseCard({c}){const nav=useNavigate();return <Card className="p-5 interactive"><div className="flex justify-between gap-3"><span className="text-[10px] font-bold px-2 py-1 rounded-full bg-blue-50 text-blue-700">{c.category}</span><span className="text-[10px] text-slate-400">{c.level}</span></div><h3 className="font-extrabold mt-4">{c.title}</h3><p className="text-xs text-slate-500 leading-5 mt-2">{c.desc}</p><div className="flex gap-4 text-[10px] text-slate-400 mt-4"><span>{c.modules} modules</span><span>{c.hours} hours</span></div><button onClick={()=>nav('/learning')} className="interactive w-full mt-4 border border-slate-200 rounded-lg py-2 text-xs font-bold">Open Course</button></Card>}
function Learning(){const role=localStorage.getItem('ccRole')||'trainee';if(role==='trainer')return <TrainerCourses/>;return <><PageHead title="My Learning" sub="Your enrolled IMD learning catalogue."/><div className="grid lg:grid-cols-2 xl:grid-cols-3 gap-5">{courses.map(c=><CourseCard key={c.id} c={c}/>)}</div></>}

function TrainerCourses(){
 const nav=useNavigate();
 return <><PageHead title="My Courses" sub="Create, organize and manage the learning content you deliver to IMD personnel.">
   <button onClick={()=>nav('/trainer')} className="interactive bg-blue-600 text-white px-4 py-2 rounded-lg text-xs font-bold"><Upload className="inline mr-1" size={14}/>Create / Upload Course</button>
 </PageHead>
 <Card className="p-4 mb-5 border-blue-100 bg-blue-50/40"><div className="flex items-start gap-3"><BookOpen className="text-blue-700 mt-0.5"/><div><h3 className="font-extrabold text-sm">Trainer content workspace</h3><p className="text-xs text-slate-600 mt-1">Open a course to upload videos, PDFs and resources, manage modules, publish updates and review learner progress.</p></div></div></Card>
 <div className="grid lg:grid-cols-2 xl:grid-cols-3 gap-5">{courses.map(c=><TrainerCourseCard key={c.id} c={c}/>)}</div></>
}

function TrainerCourseCard({c}){
 const nav=useNavigate();
 return <Card className="p-5 interactive">
   <div className="flex justify-between gap-3"><span className="text-[10px] font-bold px-2 py-1 rounded-full bg-blue-50 text-blue-700">{c.category}</span><span className="text-[10px] text-slate-400">{c.level}</span></div>
   <h3 className="font-extrabold mt-4">{c.title}</h3>
   <p className="text-xs text-slate-500 leading-5 mt-2">{c.desc}</p>
   <div className="flex gap-4 text-[10px] text-slate-400 mt-4"><span>{c.modules} modules</span><span>{c.hours} hours</span><span>184 learners</span></div>
   <div className="flex items-center gap-2 mt-4"><span className="text-[10px] font-bold text-emerald-600">Published</span><span className="text-[10px] text-slate-400">· Updated 2 days ago</span></div>
   <button onClick={()=>nav(`/course/${c.id}`)} className="interactive w-full mt-4 bg-blue-600 text-white rounded-lg py-2.5 text-xs font-bold">Manage Course <ChevronRight className="inline ml-1" size={14}/></button>
 </Card>
}
function Recommended(){return <><PageHead title="Recommended for You" sub="Recommendations are based on competency gaps, role and learning history."/><Card className="p-5 mb-5 border-blue-100 bg-blue-50/40"><div className="flex items-start gap-3"><BrainCircuit className="text-blue-700"/><div><h3 className="font-extrabold">Smart recommendation explanation</h3><p className="text-xs text-slate-600 mt-1">The demo recommendation engine prioritizes Radar and NWP content because those skills are currently below your target competency level.</p></div></div></Card><div className="grid lg:grid-cols-2 gap-5">{courses.filter(c=>c.recommended).map(c=><CourseCard key={c.id} c={c}/>)}</div></>}
function Assessment(){const role=localStorage.getItem('ccRole')||'trainee';if(role==='trainer')return <TrainerAssessments/>;return <><PageHead title="Assessments" sub="Test your knowledge and track competency progress."/><div className="grid md:grid-cols-2 gap-5"><Card className="p-5 interactive"><ClipboardCheck className="text-blue-600"/><h3 className="font-extrabold mt-4">Radar Fundamentals Assessment</h3><p className="text-xs text-slate-500 mt-2">20 questions · 30 minutes · Passing score 70%</p><button className="interactive mt-5 bg-blue-600 text-white px-4 py-2.5 rounded-lg text-xs font-bold">Start Assessment</button></Card><Card className="p-5 interactive"><CheckCircle2 className="text-emerald-600"/><h3 className="font-extrabold mt-4">Forecast Communication</h3><p className="text-xs text-slate-500 mt-2">Completed · Score 84%</p><button className="interactive mt-5 border px-4 py-2.5 rounded-lg text-xs font-bold">View Result</button></Card></div></>}

function TrainerAssessments(){
 const [notice,setNotice]=useState('');
 const action=(msg)=>setNotice(msg);
 const assessments=[['Radar Fundamentals Assessment','20 questions','184 assigned','78% average'],['Forecast Communication & Warnings','15 questions','162 assigned','84% average'],['Satellite Meteorology Checkpoint','12 questions','126 assigned','81% average']];
 return <><PageHead title="Manage Assessments" sub="Create assignments, upload question banks, publish tests and review trainee results.">
   <button onClick={()=>action('New assessment draft created.')} className="interactive bg-blue-600 text-white px-4 py-2 rounded-lg text-xs font-bold"><ClipboardCheck className="inline mr-1" size={14}/>Create Assessment</button>
 </PageHead>
 {notice&&<div className="mb-5 p-3 rounded-lg bg-emerald-50 border border-emerald-100 text-xs font-bold text-emerald-700">{notice}</div>}
 <div className="grid md:grid-cols-3 gap-4 mb-5"><Kpi icon={ClipboardCheck} num="9" label="Published Assessments"/><Kpi icon={Users} num="472" label="Assigned Attempts"/><Kpi icon={TrendingUp} num="81%" label="Average Score" trend="+5% this month"/></div>
 <div className="grid xl:grid-cols-[1.3fr_.7fr] gap-5">
   <Card className="overflow-hidden"><div className="p-5 border-b"><h3 className="font-extrabold">Your Assessments</h3><p className="text-xs text-slate-500 mt-1">Manage questions, assignment settings and learner results.</p></div>
   <div>{assessments.map((a,i)=><div key={a[0]} className="p-5 border-b last:border-b-0 hover:bg-blue-50/40 transition-colors"><div className="flex flex-col md:flex-row md:items-center justify-between gap-3"><div><div className="font-extrabold text-sm">{a[0]}</div><div className="text-xs text-slate-500 mt-1">{a[1]} · {a[2]} · Average score {a[3]}</div></div><div className="flex gap-2"><button onClick={()=>action(`Editing ${a[0]}.`)} className="interactive border px-3 py-2 rounded-lg text-xs font-bold">Edit Questions</button><button onClick={()=>action(`Showing results for ${a[0]}.`)} className="interactive bg-blue-600 text-white px-3 py-2 rounded-lg text-xs font-bold">View Results</button></div></div></div>)}</div></Card>
   <div className="space-y-5">
     <Card className="p-5"><h3 className="font-extrabold">Upload Question Bank</h3><p className="text-xs text-slate-500 mt-1">Import MCQs from CSV, Excel or a document for review before publishing.</p><label className="mt-4 h-32 border-2 border-dashed border-blue-200 rounded-xl grid place-items-center text-center cursor-pointer hover:bg-blue-50 transition-colors"><input type="file" className="hidden" accept=".csv,.xlsx,.pdf,.doc,.docx"/><div><Upload className="mx-auto text-blue-600"/><div className="font-bold text-xs mt-2">Choose question file</div><div className="text-[10px] text-slate-400 mt-1">CSV · XLSX · PDF · DOCX</div></div></label><button onClick={()=>action('Question bank queued for validation.')} className="interactive w-full mt-4 border border-slate-200 rounded-lg py-2.5 text-xs font-bold">Validate & Import</button></Card>
     <Card className="p-5"><h3 className="font-extrabold">Assignment Controls</h3><div className="space-y-2 mt-4">{[['Assign by','Department / Role'],['Attempts','1–3 attempts'],['Time limit','Configurable'],['Results','Immediate / Scheduled']].map(([a,b])=><div className="flex justify-between p-3 rounded-lg bg-slate-50 text-xs" key={a}><span className="text-slate-500">{a}</span><b>{b}</b></div>)}</div></Card>
   </div>
 </div></>
}

function ManageCourse(){
 const {id}=requireParams();
 const course=courses.find(x=>String(x.id)===String(id))||courses[0];
 const [notice,setNotice]=useState('');
 const [active,setActive]=useState('content');
 const [modules,setModules]=useState(course.modules);
 const action=(msg)=>setNotice(msg);
 return <><PageHead title={course.title} sub="Manage course content, resources, publishing and learner progress.">
   <button onClick={()=>action('Course changes saved in demo mode.')} className="interactive bg-blue-600 text-white px-4 py-2 rounded-lg text-xs font-bold">Save Changes</button>
 </PageHead>
 {notice&&<div className="mb-5 p-3 rounded-lg bg-emerald-50 border border-emerald-100 text-xs font-bold text-emerald-700">{notice}</div>}
 <div className="flex gap-2 border-b border-slate-200 mb-5 overflow-auto"><button onClick={()=>setActive('overview')} className={`tab-button ${active==='overview'?'tab-active':''}`}>Overview</button><button onClick={()=>setActive('content')} className={`tab-button ${active==='content'?'tab-active':''}`}>Course Content</button><button onClick={()=>setActive('learners')} className={`tab-button ${active==='learners'?'tab-active':''}`}>Learners & Progress</button></div>
 {active==='overview'&&<div className="grid lg:grid-cols-2 gap-5"><Card className="p-5"><h3 className="font-extrabold">Course details</h3><div className="grid md:grid-cols-2 gap-4 mt-5"><Field label="Course title" value={course.title}/><Field label="Category" value={course.category}/><Field label="Level" value={course.level}/><Field label="Duration" value={`${course.hours} hours`}/></div><label className="text-xs font-bold text-slate-600 block mt-4">Description</label><textarea className="w-full mt-2 border border-slate-200 rounded-lg p-3 text-sm h-28" defaultValue={course.desc}/></Card><Card className="p-5"><h3 className="font-extrabold">Publishing</h3><div className="p-4 mt-4 rounded-xl bg-emerald-50 border border-emerald-100"><div className="font-bold text-sm text-emerald-700">Published</div><div className="text-xs text-slate-500 mt-1">Visible to assigned IMD learners.</div></div><button onClick={()=>action('Course unpublished in demo mode.')} className="interactive w-full mt-4 border border-slate-200 rounded-lg py-2.5 text-xs font-bold">Unpublish Course</button></Card></div>}
 {active==='content'&&<div className="grid xl:grid-cols-[1.35fr_.65fr] gap-5"><Card className="p-5"><div className="flex items-center justify-between"><div><h3 className="font-extrabold">Modules & Lessons</h3><p className="text-xs text-slate-500 mt-1">{modules} modules · drag-and-drop ordering represented in demo.</p></div><button onClick={()=>{setModules(modules+1);action('New module added.')}} className="interactive border px-3 py-2 rounded-lg text-xs font-bold">+ Add Module</button></div><div className="mt-5 space-y-3">{Array.from({length:Math.min(modules,6)},(_,i)=><div key={i} className="p-4 border border-slate-200 rounded-xl hover:border-blue-300 hover:shadow-sm transition-all"><div className="flex items-center justify-between"><div><div className="font-bold text-sm">Module {i+1}: {['Introduction & Fundamentals','Operational Concepts','Interpretation Techniques','Case Studies','Practical Exercises','Final Review'][i]}</div><div className="text-[10px] text-slate-400 mt-1">Video · PDF · Quiz · Resource files</div></div><button onClick={()=>action(`Editing Module ${i+1}.`)} className="interactive text-xs font-bold text-blue-700">Edit</button></div></div>)}</div></Card><Card className="p-5"><h3 className="font-extrabold">Upload Content</h3><p className="text-xs text-slate-500 mt-1">Attach videos, presentations, PDFs and supporting resources.</p><div className="space-y-3 mt-5">{[['Upload Video','MP4 / WebM',Upload],['Upload PDF / Slides','PDF / PPTX',BookOpen],['Upload Resource','ZIP / DOCX / XLSX',DatabaseZap]].map(([label,types,I])=><label key={label} className="block p-4 border border-slate-200 rounded-xl cursor-pointer hover:border-blue-300 hover:bg-blue-50/50 transition-all"><input type="file" className="hidden" accept={types.includes('MP4')?'.mp4,.webm':types.includes('PDF')?'.pdf,.ppt,.pptx':'.zip,.doc,.docx,.xlsx'}/><div className="flex items-center gap-3"><div className="w-9 h-9 rounded-lg bg-blue-50 text-blue-700 grid place-items-center"><I size={17}/></div><div><div className="font-bold text-xs">{label}</div><div className="text-[10px] text-slate-400 mt-1">{types}</div></div><ChevronRight className="ml-auto" size={15}/></div></label>)}</div><button onClick={()=>action('Selected content is ready to upload in demo mode.')} className="interactive w-full mt-4 bg-blue-600 text-white rounded-lg py-2.5 text-xs font-bold">Upload Selected Content</button></Card></div>}
 {active==='learners'&&<div className="grid md:grid-cols-3 gap-5"><Kpi icon={Users} num="184" label="Assigned Learners"/><Kpi icon={Activity} num="68%" label="Average Progress"/><Kpi icon={CheckCircle2} num="74%" label="Completion Rate"/><Card className="md:col-span-3 p-5"><h3 className="font-extrabold">Learner progress</h3><div className="mt-4 h-3 bg-slate-100 rounded-full"><div className="h-3 bg-blue-600 rounded-full" style={{width:'68%'}}/></div><p className="text-xs text-slate-500 mt-2">184 learners assigned · 125 active · 43 completed</p></Card></div>}
 </>}
function requireParams(){return {id:window.location.pathname.split('/').filter(Boolean).pop()}}
function Certificate(){return <><PageHead title="Certificates" sub="Your earned IMD learning credentials."/><Card className="p-6 max-w-3xl"><div className="flex gap-4 items-center"><div className="w-16 h-16 rounded-xl bg-blue-50 text-blue-700 grid place-items-center"><Award size={30}/></div><div><h3 className="font-extrabold">Forecast Communication & Warnings</h3><p className="text-xs text-slate-500 mt-1">Issued 18 Aug 2026 · Certificate ID CC-IMD-2026-10482</p></div></div><button className="interactive mt-6 bg-blue-600 text-white px-5 py-2.5 rounded-lg text-xs font-bold">Download Certificate</button></Card></>}
function Profile({role}){const p=profiles[role];return <><PageHead title={`${p.label} Profile`} sub={`Manage the ${role} account and professional details.`}/><Card className="max-w-3xl p-6"><div className="flex gap-4 items-center"><div className="w-16 h-16 rounded-full bg-gradient-to-br from-slate-500 to-slate-300 grid place-items-center text-white font-black">{p.initials}</div><div><h3 className="font-extrabold">{p.name}</h3><p className="text-xs text-slate-500">{p.label} · India Meteorological Department</p></div></div><div className="grid md:grid-cols-2 gap-4 mt-7 pt-6 border-t"><Field label="Email" value={`${p.id.toLowerCase()}@imd.gov.in`}/><Field label="Employee ID" value={p.id}/><Field label="Department" value={p.department}/><Field label="Role" value={p.label}/></div><button className="interactive mt-5 bg-blue-600 text-white px-5 py-2.5 rounded-lg text-xs font-bold">Save Changes</button></Card></>}
function Field({label,value}){return <div><label className="text-xs font-bold text-slate-600">{label}</label><input className="w-full mt-2 border border-slate-200 rounded-lg h-10 px-3 text-sm" defaultValue={value}/></div>}
function Feedback(){return <><PageHead title="Feedback" sub="Help us improve learning experiences for IMD personnel."/><Card className="max-w-2xl p-6"><h3 className="font-extrabold">How was your recent learning experience?</h3><div className="flex gap-2 my-5">{['😞','😐','🙂','😀','🤩'].map(x=><button className="interactive w-12 h-12 border rounded-xl text-xl" key={x}>{x}</button>)}</div><textarea className="w-full h-32 border rounded-lg p-3 text-sm" placeholder="Tell us what worked well or what could be improved..."/><button className="interactive mt-4 bg-blue-600 text-white px-5 py-2.5 rounded-lg text-xs font-bold">Submit Feedback</button></Card></>}
function Trainer(){return <><PageHead title="Trainer Studio" sub="Create assessments and learning content for meteorological teams."/><div className="grid lg:grid-cols-2 gap-5"><Card className="p-5"><h3 className="font-extrabold">AI-assisted MCQ Generator</h3><p className="text-xs text-slate-500 mt-1">Upload lecture notes, slides or PDFs and generate draft questions for review.</p><div className="h-44 mt-5 border-2 border-dashed border-blue-200 rounded-xl grid place-items-center text-center interactive"><div><Upload className="mx-auto text-blue-600"/><div className="font-bold text-sm mt-2">Upload PDF / PPT / Document</div><div className="text-[10px] text-slate-400 mt-1">Drag & drop or click to browse</div></div></div><button className="interactive w-full mt-4 border border-slate-200 rounded-lg py-2.5 text-xs font-bold">Generate Questions</button></Card><Card className="p-5"><h3 className="font-extrabold">AI Generated Questions</h3><ol className="mt-4 space-y-3 text-xs list-decimal pl-5">{['What is the primary use of Doppler radar?','Which band is commonly used in weather radar?','What does reflectivity indicate?','What is range ambiguity?','Which phenomenon causes ground clutter?'].map(q=><li key={q}>{q}</li>)}</ol><button className="interactive w-full mt-5 bg-blue-600 text-white rounded-lg py-2.5 text-xs font-bold">Review & Publish</button></Card></div></>}
function Admin(){return <><PageHead title="Organization Analytics" sub="Learning, participation and competency intelligence across IMD."><button className="interactive bg-white border px-4 py-2 rounded-lg text-xs font-bold">Jan 2026 — Aug 2026</button></PageHead><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4"><Kpi icon={Users} num="1,248" label="Total Trainees" trend="+8.4% YoY"/><Kpi icon={BookOpen} num="86" label="Active Courses"/><Kpi icon={Activity} num="427" label="Ongoing Training"/><Kpi icon={CheckCircle2} num="913" label="Certificates Issued"/></div><div className="grid xl:grid-cols-2 gap-5 mt-5"><Card className="p-5"><h3 className="font-extrabold">Training Participation</h3><div className="h-64 mt-3"><ResponsiveContainer width="100%" height="100%"><BarChart data={participation}><XAxis dataKey="m" fontSize={11}/><YAxis fontSize={11}/><Tooltip/><Bar dataKey="v" fill={blue} radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></Card><Card className="p-5"><h3 className="font-extrabold">Course Completion Rate</h3><div className="h-64"><ResponsiveContainer><PieChart><Pie data={completion} dataKey="value" nameKey="name" innerRadius={65} outerRadius={95}>{completion.map((x,i)=><Cell key={x.name} fill={['#16a579','#0868df','#cbd5e1'][i]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div><div className="flex justify-center gap-5 text-xs">{completion.map(x=><span key={x.name}>{x.name} {x.value}%</span>)}</div></Card></div><div className="grid xl:grid-cols-3 gap-5 mt-5"><Insight icon={TrendingUp} title="Completion improving" text="Completion is up 12% compared with the previous reporting period."/><Insight icon={BrainCircuit} title="Recommendation impact" text="Recommended courses show 1.7× higher enrolment conversion in this demo dataset."/><Insight icon={Activity} title="Optimization opportunity" text="Peak usage suggests shifting non-critical jobs outside high-demand windows."/></div></>}
function Insight({icon:I,title,text}){return <Card className="p-5 interactive"><I className="text-blue-600" size={20}/><h3 className="font-extrabold mt-3 text-sm">{title}</h3><p className="text-xs text-slate-500 mt-2 leading-5">{text}</p></Card>}
function Heatmap(){return <><PageHead title="Department-wise Competency Heatmap" sub="Identify skill gaps across IMD divisions and prioritize interventions."><div className="flex gap-2"><button className="interactive bg-white border px-3 py-2 rounded-lg text-xs font-bold"><Filter className="inline mr-1" size={13}/>All Departments</button><button className="interactive bg-blue-600 text-white px-3 py-2 rounded-lg text-xs font-bold">Export</button></div></PageHead><Card className="p-5 overflow-auto"><table className="w-full text-xs border-separate border-spacing-1"><thead><tr><th className="text-left p-3">Department</th>{['Forecasting','Radar','Satellite','NWP','Climate','Communication'].map(x=><th key={x} className="bg-slate-100 p-3">{x}</th>)}</tr></thead><tbody>{heatRows.map(([d,vals])=><tr key={d}><th className="text-left p-3 font-bold">{d}</th>{vals.map((v,i)=><td key={i} className={`p-4 text-center rounded-md font-bold ${v===3?'bg-emerald-300 text-emerald-900':v===2?'bg-amber-200 text-amber-900':'bg-red-300 text-red-900'}`}>{v===3?'High':v===2?'Moderate':'Low'}</td>)}</tr>)}</tbody></table><div className="flex justify-center gap-6 text-xs mt-5"><span>🟢 High</span><span>🟡 Moderate</span><span>🔴 Low</span></div></Card></>}
function Optimization(){const data=[{t:'00',v:32},{t:'04',v:28},{t:'08',v:54},{t:'12',v:82},{t:'16',v:91},{t:'20',v:67},{t:'24',v:38}];return <><PageHead title="Load Optimization & Platform Health" sub="Demo view of capacity-aware routing, service health and workload balancing."><span className="inline-flex items-center gap-2 text-xs bg-emerald-50 text-emerald-700 px-3 py-2 rounded-lg font-bold"><Activity size={15}/> All systems operational</span></PageHead><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4"><Kpi icon={ServerCog} num="42%" label="Current Load" trend="18% below threshold"/><Kpi icon={Activity} num="99.96%" label="API Availability"/><Kpi icon={DatabaseZap} num="184 ms" label="Avg. Response" trend="↓ 22 ms"/><Kpi icon={RefreshCw} num="3" label="Active Service Nodes"/></div><div className="grid xl:grid-cols-[1.4fr_.8fr] gap-5 mt-5"><Card className="p-5"><div className="flex justify-between"><h3 className="font-extrabold">Projected Platform Load</h3><span className="text-xs text-slate-400">24h window</span></div><div className="h-64 mt-3"><ResponsiveContainer width="100%" height="100%"><LineChart data={data}><XAxis dataKey="t" fontSize={11}/><YAxis fontSize={11}/><Tooltip/><Line type="monotone" dataKey="v" stroke={blue} strokeWidth={3}/></LineChart></ResponsiveContainer></div></Card><Card className="p-5"><h3 className="font-extrabold">Optimization Controls</h3><div className="mt-4 space-y-3">{[['Traffic routing','Adaptive'],['Background jobs','Off-peak'],['Course recommendations','Cached'],['Analytics queries','Read replica']].map(([a,b])=><div key={a} className="p-3 rounded-lg bg-slate-50 flex justify-between text-xs"><span>{a}</span><b className="text-blue-700">{b}</b></div>)}</div><div className="mt-5 p-4 bg-blue-50 rounded-xl"><div className="flex items-center gap-2 font-bold text-xs"><ShieldCheck size={15} className="text-blue-700"/> Security posture</div><p className="text-[10px] text-slate-500 mt-2">JWT authentication, RBAC authorization and Nginx reverse-proxy/load-balancing are represented as planned production architecture.</p></div></Card></div></>}
function UserManagement(){return <><PageHead title="User Management" sub="Demo administration workspace for role-based access control."><button className="interactive bg-blue-600 text-white px-4 py-2 rounded-lg text-xs font-bold">+ Add User</button></PageHead><Card className="overflow-auto"><table className="w-full text-xs"><thead className="bg-slate-50"><tr>{['Name','Employee ID','Department','Role','Status','Last Active'].map(x=><th className="text-left p-4" key={x}>{x}</th>)}</tr></thead><tbody>{[['Rahul Sharma','IMD-TR-10482','Forecasting','Trainee','Active','Today'],['Dr. Meera Iyer','IMD-TN-00211','Training','Trainer','Active','Today'],['Amit Verma','IMD-AD-00034','Administration','Admin','Active','2 hrs ago'],['Priya Nair','IMD-TR-08912','Radar','Trainee','Active','Yesterday'],['Arjun Singh','IMD-TR-09331','Satellite','Trainee','Inactive','8 days ago']].map(r=><tr className="border-t hover:bg-blue-50/40" key={r[1]}>{r.map((x,i)=><td className="p-4" key={i}>{i===4?<span className={`px-2 py-1 rounded-full text-[10px] font-bold ${x==='Active'?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{x}</span>:x}</td>)}</tr>)}</tbody></table></Card></>}

createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>)
